import { RoomPage } from "./room_interface";

export const all_rooms: RoomPage[] = [
	{
		id: 1,
		name: "Presidential Suit",
		route: "presidential-suit",
		description:
			"The Presidential Suite is the most luxurious room in the hotel. It is a two-bedroom suite with a separate living room, dining room, kitchen, and a private balcony. The suite is perfect for families or guests who want to experience the ultimate luxury.",
		price: 40000,
		bed_size: "King Size",
		no_of_guests: 4,
		image1: "/assets/room1.svg",
		image2: "/assets/room2.svg",
		image3: "/assets/room3.svg",
		image4: "/assets/room1.svg",
		image5: "/assets/room1.svg",
	},
	{
		id: 2,
		name: "Executive Room",
		route: "executive-room",
		description:
			"The Executive Room is a spacious room with a king-size bed, a separate living area, and a private balcony. The room is perfect for business travelers or guests who want a little extra space to relax and unwind.",
		price: 30000,
		bed_size: "King Size",
		no_of_guests: 4,
		image1: "/assets/room1.svg",
		image2: "/assets/room2.svg",
		image3: "/assets/room3.svg",
		image4: "/assets/room1.svg",
		image5: "/assets/room1.svg",
	},
	{
		id: 3,
		name: "Standard Room",
		route: "standard-room",
		description:
			"The Standard Room is a comfortable room with a king-size bed and a private balcony. The room is perfect for couples or solo travelers looking for a cozy and relaxing stay.",
		price: 25000,
		bed_size: "King Size",
		no_of_guests: 4,
		image1: "/assets/room1.svg",
		image2: "/assets/room2.svg",
		image3: "/assets/room3.svg",
		image4: "/assets/room1.svg",
		image5: "/assets/room1.svg",
	},
	{
		id: 4,
		name: "Kings Size Room 1",
		route: "kings-size-room-1",
		description:
			"The Kings Size Room 1 is a spacious room with a king-size bed, a separate living area, and a private balcony. The room is perfect for business travelers or guests who want a little extra space to relax and unwind.",
		price: 25000,
		bed_size: "King Size",
		no_of_guests: 4,
		image1: "/assets/room1.svg",
		image2: "/assets/room2.svg",
		image3: "/assets/room3.svg",
		image4: "/assets/room1.svg",
		image5: "/assets/room1.svg",
	},
	{
		id: 5,
		name: "Kings Single Room 2",
		route: "kings-single-room-2",
		description:
			"The Kings Single Room 2 is a comfortable room with a king-size bed and a private balcony. The room is perfect for couples or solo travelers looking for a cozy and relaxing stay.",
		price: 20000,
		bed_size: "King Size",
		no_of_guests: 4,
		image1: "/assets/room1.svg",
		image2: "/assets/room2.svg",
		image3: "/assets/room3.svg",
		image4: "/assets/room1.svg",
		image5: "/assets/room1.svg",
	},
];
